### ISSUE TITLE
PLZ Suche funktioniert nicht

### ISSUE THREAD

**Issue by r1sim** [okfde/rettedeinennahverkehr#7]
Aktuell kommt bei jeder PLZ die auf der Website eingegeben wird diese Meldung, egal welche PLZ eingetragen wird: 
![image](https://user-images.githubusercontent.com/9327096/81744858-0ead3080-94a4-11ea-8527-131675865248.png)

Das liegt daran, dass in [Google Sheets](https://docs.google.com/spreadsheets/d/1MNPMJGdsoKYNwmdMAE3R8rZSO0B5jxrtlvadrFfMyQ8/edit#gid=0&range=A1) die Spalte "AdminCode3" (vermutlich aus Versehen) in "l" umbenannt wurde.

In https://github.com/okfde/rettedeinennahverkehr/blob/master/js/lobbyingo.js#L155 wird daher nur ein Objekt in `lkrData` eingefügt und die Suche schlägt immer fehl.

**Comment by robbi5** [comment]
Hui! Danke für den Hinweis, habs grade im Sheet gefixt :)
